### ISSUE TITLE
Standardize Python Code Formatting with Unified Linter Configuration

### ISSUE THREAD

**Issue by neelam-kushwah** [eclipse-uprotocol/up-tck#47]
To ensure consistent code quality and style across the project, we need to standardize our Python code formatting by using a unified linter configuration. This will help avoid formatting-related changes in PR and maintain a clean, readable codebase.

Decide on a linter to use(Black, Flake8, pylint etc)
Create a linter configuration file with desired settings, and ensures it runs as part of the CI pipeline. 
Share the formatter configuration to the team.

**Comment by matthewd0123** [comment]
First, just a bit of info on code on Flake8. https://flake8.pycqa.org/en/2.5.5/
Flake8 is a wrapper around the pep8 lib as well as a complexity checker, and an error checker. So, hopefully anything it complains about would be aligned with pep8 standards

here is what I have done for the 1.5.8 up-python PR. We can decide to modify this, but it's the standard I've been running the code against:

flake8 --ignore E203,W503,W504,F811 . --exclude *_pb2.py --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

max-line-length=79: This is based on here:
https://peps.python.org/pep-0008/#maximum-line-length
Pep8 says to keep max line length at 79

max-complexity 10:
I just think this is nice, but doesn't have to be like this. not really a formatting thing

Next there are a few pep8 standards that are being ignored for various reasons:

https://www.flake8rules.com/rules/E203.html
E203 is ignored because in certain circumstances, you'll be using a hanging ":" in your code, and it's not necessarily wrong to do it like that.
https://github.com/PyCQA/pycodestyle/issues/373

W503,W504
https://stackoverflow.com/questions/57074300/what-is-the-recommended-way-to-break-a-long-if-statement-w504-line-break-after
These are contradictory steps that require you to both put the + in a multiline line before the line break and after the line break. So, I comment them both out

F811
https://www.flake8rules.com/rules/F811.html
This one is about redefining functions. It needs be ignored in our code specifically when multimethod is being used.

**Comment by matthewd0123** [comment]
My thoughts:

Blackformatter is the formatter that calls itself an "pep8 compliant opinionated formatter". Flake8 doesn't do formatting, it just checks our code against pep8 and complexity and errors.

The 79 character limit is the thing that starts making our code a bit unreadable, in my opinion... mainly lines that start using parentheses. but, solution to this would be to make code lines shorter so we don't have to use those parentheses.

**Comment by neelam-kushwah** [comment]
Black has become quite popular in the Python community, but it is a third-party tool and not officially part of the Python standard library.

In my opinion, our code should follow the standard PEP 8 guidelines. We shouldn’t force users to use a specific formatter; the only thing that matters is adherence to PEP 8. Each IDE has its own default formatter that follows PEP 8 guidelines as well.

We can use pylint in CI to check whether our code follows the PEP 8 guidelines or not.

Additionally, when creating a PR, it should contain only relevant changes. We should not alter the formatting of existing code unnecessarily. Before committing, we should review the differences in the code, verify them, and then commit.

@eeshakotla , please provide your inputs too.

**Comment by princemac** [comment]
In my opinion we can go either with **Flake 8** or **Pylint**.

Flake8 if you prioritize simplicity, quick setup, and adherence to PEP 8 and other coding standards. Pylint if you need more comprehensive static code analysis, including potential bugs, code smells, and adherence to best practices beyond PEP 8.

Flake8 offers flexibility in configuration, minimalist setup, allowing you to customize which checks are applied and adjust settings. 

@matthewd0123 We can configure Flake8 for **max-line-length**.

**Comment by princemac** [comment]
Yeah. So, we can use Autopep8 if we wanna follow **PEP 8 style guide**. While Black imposes its own formatting rules.

We can integrate any of it to the CI/CD  to ensures consistent code formatting. If formatter detects any formatting issues, then 
we can ensure that the CI/CD pipeline fails to prevent code with formatting violations from being merged or deployed.

**Comment by neelam-kushwah** [comment]
@princemac , Let's start by adding a linter workflow to all Python repositories.

**Comment by neelam-kushwah** [comment]
@evshary , Could you please check with your team which Python code formatter they use, whether it's the default one or a specific formatter?

**Comment by KotlaEesha** [comment]
Ruff is another option which we can look at.

It combines linting and some level of auto-fixing capabilities. It supports a wide range of linting rules from various popular linters, including flake8, isort, and pyflakes making it a versatile tool for ensuring code quality and style.
 
Here are some insights on Ruff
https://pypi.org/project/ruff/

**Comment by matthewd0123** [comment]
up-tck workflow is already configured to use flake8 formatter btw

**Comment by neelam-kushwah** [comment]
@princemac @matthewd0123 @KotlaEesha , I really like Ruff because of its flexibility and extensive use in major open-source projects. I've created a configuration file to customize its settings. If everyone agrees, I suggest enabling Ruff's linting and formatting checks for all Python repositories. 

# ruff.toml

line-length = 99
indent-width = 4

# Exclude specific files or directories.
exclude = [
    "build/",
    "dist/",
    ".venv/",
    "__pycache__/",
]

[lint]
# Enable all basic PEP 8 checks and other common linting rules.
select = [
    "E", # PEP 8 rules (formatting issues)
    "F", # Pyflakes rules (undefined names, etc.)
    "W", # Additional PEP 8 rules (warning-level issues)
    "I", # Import order checker (ensuring imports are ordered correctly)
    "ERA" # flake8-eradicate (identifying commented-out code)
]

[lint.flake8-annotations]
allow-star-arg-any = true

[format]
quote-style = "preserve"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 60

**Comment by neelam-kushwah** [comment]
To address the linting errors using Ruff, follow these steps:

Install Ruff:

`pip install ruff`

Check for Lint Errors: Run the following command to display all lint errors:

`ruff check --config .\.github\ruff.toml`

To fix most of the reported issues, execute:

`ruff check --config .\.github\ruff.toml --fix`

Run the following command to display all format errors:

`ruff format --check --config .\.github\ruff.toml`

To fix all format issues, execute:
`ruff format --config .\.github\ruff.toml `

By following above steps, you should be able to identify and correct the majority of linting and all format errors in the codebase efficiently.

**Comment by matthewd0123** [comment]
Ruff looks great! Will integrate that into the tck. Looks similar to rust's formatting tools.

One question: do you guys think that we can say that we'll be the main maintainers on the python projects? if so, 99 characters sounds fine... but still need to format all the comments and docstrings to 72 characters

"

Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters.
"

https://peps.python.org/pep-0008/#:~:text=The%20Python%20standard%20library%20is,inside%20parentheses%2C%20brackets%20and%20braces.

@Neelam if this 99/72 character combo is acceptable, I will implement it in the 1.5.8 PR. Please advise.

**Comment by neelam-kushwah** [comment]
While PEP 8 guidelines suggest a maximum line length of 79 characters, it’s not a strict mandate. The primary objective is to ensure code readability. Many popular IDEs default to a 120-character limit, and numerous major open-source projects adopt limits of 99, 88, or 120 characters. A 79-character limit can sometimes hinder readability, hence, I lean towards a 120-character limit, same as Java’s standard. This not only maintains readability but also enhances the code’s visual appeal. Ultimately, the choice of line length may vary based on team preferences and project specifics.

**Comment by matthewd0123** [comment]
okay okay that sounds good just tell me what length to do, 99 or 120

**Comment by matthewd0123** [comment]
all of pep8 is a suggestion, sure, but if you don't follow one of the rules then you're no longer pep8-compliant
